name: fender
services:
  db:
    user: root
    image: amazon/dynamodb-local:latest
    restart: always
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data
    ports:
      - 8000:8000
    volumes:
      - ddb-local:/home/dynamodblocal/data
  
  db-admin:
    image: aaronshaf/dynamodb-admin:latest
    restart: always
    ports:
      - 8001:8001
    environment:
      DYNAMO_ENDPOINT: http://db:8000
    depends_on:
      - db

  backend:
    build: .
    restart: always
    ports:
      - 8080:8000
    env_file:
      - .env
    depends_on:
      - db

volumes:
  ddb-local: